darbuotoju valdymos sistema/Controllers/TasksController.cs
using darbuotoju_valdymos_sistema.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace darbuotoju_valdymos_sistema.Controllers
{
    public class TasksController : Controller
    {
        private readonly ILogger<TasksController> _logger;

        public TasksController(ILogger<TasksController> logger)
        {
            _logger = logger;
        }

        public IActionResult Tasks(string sortOrder, string term)
        {
            ViewData["IdSortParam"] = sortOrder == "id" ? "id_desc" : "id";
            ViewData["NameSortParam"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            term = String.IsNullOrEmpty(term) ? "" : term;
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;

            var tasks = context.GetAllTasks().ToList();
            
            if (term != "")
            {
                var lTerm = term.ToLower();
                tasks = tasks.Where(n => n.id.ToString().Contains(lTerm) || n.name.ToLower().Contains(lTerm) || n.workers.Any(x => x.name.ToLower().Contains(lTerm)) || n.workers.Any(x => x.lastName.ToLower().Contains(lTerm))).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    tasks = tasks.OrderBy(n => n.status == true).ThenByDescending(n => n.name).ToList();
                    break;
                case "id_desc":
                    tasks = tasks.OrderBy(n => n.status == true).ThenByDescending(n => n.id).ToList();
                    break;
                case "name":
                    tasks = tasks.OrderBy(n => n.status == true).ThenBy(n => n.name).ToList();
                    break;
                case "id":
                    tasks = tasks.OrderBy(n => n.status == true).ThenBy(n => n.id).ToList();
                    break;
                case "date_desc":
                    tasks = tasks.OrderBy(n => n.status == true).ThenByDescending(n => n.dueby).ToList();
                    break;
                default:
                    tasks = tasks.OrderBy(n => n.status == true).ThenBy(n => n.dueby).ToList();
                    break;
            }
            return View(tasks);
        }
        public IActionResult UpdateTasksExcludedSearch(string term, int userid)
        {
            term = String.IsNullOrEmpty(term) ? "" : term;
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;

            List<darbuotoju_valdymos_sistema.Models.Task> tasks = context.GetTasksAssignedToWorker(userid);
            List<darbuotoju_valdymos_sistema.Models.Task> excluded = context.GetAllTasks(tasks);

            if (term != "")
            {
                var lTerm = term.ToLower();
                excluded = excluded.Where(n => n.id.ToString().Contains(lTerm) || n.name.ToLower().Contains(lTerm)).ToList();
            }
            return PartialView("_ExcludedTasks", excluded);
        }

        public IActionResult TaskInfo(int id)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var tasks = context.GetTaskById(id);
            return PartialView("_ModalTaskView", tasks);
        }
        public IActionResult AddTask(int userid, int taskid)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var userInfo = context.AssignTaskToWorker(userid, taskid);
            return PartialView("_ModalWorkerView", userInfo);
        }
        public IActionResult RemoveTask(int userid, int taskid)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var userInfo = context.RemoveTaskFromWorker(userid, taskid);
            return PartialView("_ModalWorkerView", userInfo);
        }
        public void DeleteTask(int taskid)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            context.RemoveTask(taskid);
        }
        public IActionResult RemoveTaskAs(int userid, int taskid)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var userInfo = context.RemoveTaskFromWorker(userid, taskid);
            return PartialView("_ModalWorkerView", userInfo);
        }

        public IActionResult CreateTaskWindow(string name)
        {
            return PartialView("_ModalNewTaskForm");
        }
        public IActionResult UpdateTasksTableSearch(string sortOrder, string term)
        {
            ViewData["IdSortParam"] = sortOrder == "id" ? "id_desc" : "id";
            ViewData["NameSortParam"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            term = String.IsNullOrEmpty(term) ? "" : term;
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;

            var tasks = context.GetAllTasks().ToList();
            if (term != "")
            {
                var lTerm = term.ToLower();
                tasks = tasks.Where(n => n.id.ToString().Contains(lTerm) || n.name.ToLower().Contains(lTerm) || n.workers.Any(x => x.name.ToLower().Contains(lTerm)) || n.workers.Any(x => x.lastName.ToLower().Contains(lTerm))).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    tasks = tasks.OrderBy(n => n.status == true).ThenByDescending(n => n.name).ToList();
                    break;
                case "id_desc":
                    tasks = tasks.OrderBy(n => n.status == true).ThenByDescending(n => n.id).ToList();
                    break;
                case "name":
                    tasks = tasks.OrderBy(n => n.status == true).ThenBy(n => n.name).ToList();
                    break;
                case "id":
                    tasks = tasks.OrderBy(n => n.status == true).ThenBy(n => n.id).ToList();
                    break;
                case "date_desc":
                    tasks = tasks.OrderBy(n => n.status == true).ThenByDescending(n => n.dueby).ToList();
                    break;
                default:
                    tasks = tasks.OrderBy(n => n.status == true).ThenBy(n => n.dueby).ToList();
                    break;
            }

            return PartialView("_MainTasksView", tasks);
        }
        public void MarkTaskAsDone(int id)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            context.MarkTaskAsDone(id);
        }
        public void CreateNewTask(string name, string description, DateTime duebydate, long createddate)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            context.CreateNewTask(name, description, duebydate, createddate);
        }
        public void UpdateTask(int id,string name, string description, DateTime duebydate, bool status)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            context.UpdateTask(id, name, description, duebydate, status);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

darbuotoju valdymos sistema/Controllers/WorkersController.cs
using darbuotoju_valdymos_sistema.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace darbuotoju_valdymos_sistema.Controllers
{
    public class WorkersController : Controller
    {
        private readonly ILogger<WorkersController> _logger;

        public WorkersController(ILogger<WorkersController> logger)
        {
            _logger = logger;
        }

        public IActionResult Workers(string sortOrder)
        {
            ViewData["IdSortParam"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["NameSortParam"] = sortOrder == "name" ? "name_desc" : "name";

            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var workers = context.GetAllWorkers().ToList();
            switch (sortOrder)
            {
                case "name_desc":
                    workers = workers.OrderByDescending(n => n.name).ToList();
                    break;
                case "id_desc":
                    workers = workers.OrderByDescending(n => n.id).ToList();
                    break;
                case "name":
                    workers = workers.OrderBy(n => n.name).ToList();
                    break;
                default:
                    workers = workers.OrderBy(n => n.id).ToList();
                    break;
            }
            return View(workers);
        }
        public IActionResult WorkerInfo(int id)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var worker = context.GetWorkerById(id);
            return PartialView("_ModalWorkerView", worker);
        }

        public void CreateNewWorker(string name, string lastname)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            context.CreateNewWorker(name, lastname);
            //return PartialView("_ModalWorkerView");
        }

        public void DeleteWorker(int id)
        {
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            context.RemoveWorker(id);
            //return PartialView("_ModalWorkerView");
        }

        public IActionResult CreateWorkerWindow(string name)
        {
            return PartialView("_ModalNewWorkerForm");
        }
        public IActionResult UpdateWorkersTable(string sortOrder)
        {
            ViewData["IdSortParam"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["NameSortParam"] = sortOrder == "name" ? "name_desc" : "name";

            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;
            var workers = context.GetAllWorkers().ToList();
            switch (sortOrder)
            {
                case "name_desc":
                    workers = workers.OrderByDescending(n => n.name).ToList();
                    break;
                case "id_desc":
                    workers = workers.OrderByDescending(n => n.id).ToList();
                    break;
                case "name":
                    workers = workers.OrderBy(n => n.name).ToList();
                    break;
                default:
                    workers = workers.OrderBy(n => n.id).ToList();
                    break;
            }
            return PartialView("_MainWorkersWindow", workers);
        }
        public IActionResult UpdateWorkersTableSearch(string sortOrder, string term)
        {
            ViewData["IdSortParam"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["NameSortParam"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["LastnameSortParam"] = sortOrder == "lastname" ? "lastname_desc" : "lastname";
            term = String.IsNullOrEmpty(term) ? "" : term;
            DBContext context = HttpContext.RequestServices.GetService(typeof(DBContext)) as DBContext;

            var workers = context.GetAllWorkers().ToList();
            if (term != "")
            {
                var lTerm = term.ToLower();
                workers = workers.Where(n => n.id.ToString().Contains(lTerm) || n.name.ToLower().Contains(lTerm) || n.lastName.ToLower().Contains(lTerm) || n.tasks.Any(x => x.name.ToLower().Contains(lTerm))).ToList();
            }

                switch (sortOrder)
                {
                    case "name_desc":
                        workers = workers.OrderByDescending(n => n.name).ToList();
                        break;
                    case "id_desc":
                        workers = workers.OrderByDescending(n => n.id).ToList();
                        break;
                    case "name":
                        workers = workers.OrderBy(n => n.name).ToList();
                        break;
                    case "lastname":
                        workers = workers.OrderByDescending(n => n.lastName).ToList();
                        break;
                    case "lastname_desc":
                        workers = workers.OrderBy(n => n.lastName).ToList();
                        break;
                    default:
                        workers = workers.OrderBy(n => n.id).ToList();
                        break;
                }
            
            return PartialView("_MainWorkersWindow", workers);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

darbuotoju valdymos sistema/Views/Shared/_ExcludedTasks.cshtml
@model IEnumerable<darbuotoju_valdymos_sistema.Models.Task>

<tr>
    <td>
        @foreach(var item in Model){
            <button id="addTask" onclick="addTask(@item.id)">@item.name</button>
        }
    </td>
</tr>

darbuotoju valdymos sistema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - darbuotoju_valdymos_sistema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/darbuotoju_valdymos_sistema.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">darbuotoju_valdymos_sistema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workers" asp-action="Workers">Workers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Tasks">Worker Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - darbuotoju_valdymos_sistema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

darbuotoju valdymos sistema/Views/Shared/_MainTasksView.cshtml
@model IEnumerable<darbuotoju_valdymos_sistema.Models.Task>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<table class="table">
  <thead class="thead-dark">
    <tr class="bg-secondary">
    <th class="align-middle">                   
        <button id="sortByID" class="btn btn-primary" onclick="searchFunction('@ViewData["IdSortParam"]')">Task ID</button> 
    </th>
    <th class="align-middle">
        <button id="sortByName" class="btn btn-primary" onclick="searchFunction('@ViewData["NameSortParam"]')">Task Name</button> 
    </th >
    <th class="align-middle">
        Created at
    </th>
    <th class="align-middle">
        <button id="sortByDate" class="btn btn-primary" onclick="searchFunction('@ViewData["DateSortParam"]')">Due by date</button> 
    </th>
    <th class="align-middle">
        Workers assigned
    </th>
    <th class="align-middle">
        Actions
    </th>


    </tr>
  </thead>
  <tbody>
  @foreach (var item in Model)
  {
    
       <tr @(item.status?"class=bg-success":"")>
        
       <td>
        @Html.DisplayFor(modelItem => item.id)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.name)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.created)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.dueby)
      </td>
      <td>
      @foreach(var worker in item.workers){
          <button id="editUser" onclick="ViewWorker(@worker.id)">@worker.name @worker.lastName</button>    
      }
      </td>
      <td>
          <button id="editTask" class="btn btn-primary" onclick="ViewTask(@item.id)">Edit Task</button> 
                @if (@item.status == false)
                {
                    <button id="markdoneTask" class="btn btn-primary" onclick="MarkAsDone(@item.id)">Mark as done</button>
                }
          <button id="deleteDelete" class="btn btn-danger" onclick="deleteTask(@item.id)">Delete Task</button> 
      </td>
      </tr>
  }
  </tbody>
</table>

darbuotoju valdymos sistema/Views/Shared/_MainWorkersWindow.cshtml
@model IEnumerable<darbuotoju_valdymos_sistema.Models.Workers>
<table class="table table-striped table-dark">

<tr>
    <th class="align-middle">                   
        <button id="sortByID" class="btn btn-primary" onclick="searchFunction('@ViewData["IdSortParam"]')">Worker identifier</button> 
    </th>
    <th class="align-middle">
        <button id="sortByName" class="btn btn-primary" onclick="searchFunction('@ViewData["NameSortParam"]')">Name</button> 
    </th>
    <th class="align-middle">
        <button id="sortByLastname" class="btn btn-primary" onclick="searchFunction('@ViewData["LastnameSortParam"]')">Lastname</button> 
    </th>
    <th class="align-middle">
        Assigned Tasks
    </th>
    <th class="align-middle">
        Actions
    </th>

  </tr>
  @foreach (var item in Model)
  {
    <tr>
      <td>
        @item.id
      </td>
      <td>
        @item.name
      </td>
      <td>
        @item.lastName
      </td>

      <td>
      @foreach(var task in item.tasks){
          <button id="taskView" class="@(task.status?"btn btn-success":"btn btn-primary")" onclick="ViewTask(@task.id)">@task.name</button> 
      }
      </td>
      <td>
          <button id="editUser" class="btn btn-primary">Edit Worker</button> 
          <button id="deleteUser" class="btn btn-danger" onclick="DeleteWorker(@item.id)">Delete Worker</button> 
      </td>
    </tr>
  }
  </table>

darbuotoju valdymos sistema/Views/Shared/_ModalNewTaskForm.cshtml
@model darbuotoju_valdymos_sistema.Models.Task
<div class="modal-content">
    <div class="modal-header">
        <button type="button" id="closebttn" class="close btn btn-primary" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create new task</h4>
    </div>
    <div class="modal-body">
        Task name:<input type="text" id="newTaskName" name="newTaskName" value=""><br>
        Task description:<textarea type="text" id="newTaskDescription" name="newTaskDescription" value=""></textarea><br>
        Task due by date:<input type="datetime-local" id="newTaskDby"name="newTaskDby" /><br>
        <button type="button" id="closebttn" class="btn btn-success" data-dismiss="modal" onclick="SaveNewTask()">Create</button>
    </div>
    <div class="modal-footer">
        <button type="button" id="closebttn" class="btn btn-primary" data-dismiss="modal">Close</button>
    </div>
</div>

darbuotoju valdymos sistema/Views/Shared/_ModalNewWorkerForm.cshtml
@model darbuotoju_valdymos_sistema.Models.Workers
<div class="modal-content">
    <div class="modal-header">
        <button type="button" id="closebttn" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create new worker</h4>
    </div>
    <div class="modal-body">
        Worker name:<input type="text" id="newWorkerName" name="newWorkerName" value=""><br>
        Worker surname:<input type="text" id="newWorkerLastname" name="newWorkerLastname" value=""><br>
        <button type="button" id="closebttn" data-dismiss="modal" onclick="SaveNewWorker()">Create</button>
    </div>
    <div class="modal-footer">
        <button type="button" id="closebttn" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</div>

darbuotoju valdymos sistema/Views/Shared/_ModalTaskView.cshtml
@model darbuotoju_valdymos_sistema.Models.Task
<div class="modal-content">
    <div class="modal-header">
        <button type="button" id="closebttn" class="close btn btn-primary" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit the task</h4>
    </div>
    <div class="modal-body">
        Task name:<input type="text" id="TaskName" name="TaskName" value="@Model.name"><br>
        Task description: <textarea type="text" id="TaskDescription" name="TaskDescription" value="@Model.description">@Model.description</textarea><br>
        Task due by date:<input type="datetime-local" id="TaskDby" name="TaskDby" defaultValue="@Model.dueby.ToString("yyyy-MM-dd'T'hh:mm")" value="@Model.dueby.ToString("yyyy-MM-dd'T'hh:mm")" /> <br>
        Task done: <input type="checkbox" id="status" name="status" @(Model.status?"checked='checked'":"")><br>
        <button type="button" id="closebttn" class="btn btn-success" data-dismiss="modal" onclick="UpdateTask(@Model.id)">Update task</button>
    </div>
    <div class="modal-footer">
        <button type="button" id="closebttn" class="btn btn-primary" data-dismiss="modal">Close</button>
    </div>
</div>

darbuotoju valdymos sistema/Views/Shared/_ModalWorkerView.cshtml
@model darbuotoju_valdymos_sistema.Models.Workers
<div class="modal-content">
    <div class="modal-header">
        <button type="button" id="closebttn" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
    </div>
    <div class="modal-body">
        Search for task:<input type="text" id="searchTaskTerm" oninput="searchTaskInWorkerView()" name="searchTaskTerm" value=""><br/>
        <table class="table" id="userTable">
            @await Html.PartialAsync("_UserDataView", Model)
         </table>
            <th>
                Unassigned Tasks
            </th>
         <table class="table" id="excludedTable">
             
            @await Html.PartialAsync("_ExcludedTasks", Model.excludedTasks)
         </table>

    </div>
    <div class="modal-footer">
        <button type="button" id="closebttn" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</div>

darbuotoju valdymos sistema/Views/Shared/_UserDataView.cshtml
@model darbuotoju_valdymos_sistema.Models.Workers

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<tr>
    <th>                   
        Identifier
    </th>
    <th>
        Mame
    </th>
    <th>
        Surname
    </th>
    <th>
        Assigned Tasks
    </th>

</tr>
<tr>
    <td id="personalUserId" data-id=@Model.id>   
        @Model.id
    </td>
    <td>   
        @Model.name
    </td>
    <td>   
        @Model.lastName
    </td>
    <td>
        @foreach(var item in Model.tasks)
        {
            <button id="removeTask" onclick="removeTask(@item.id)">@item.name</button>         
        }
    </td>
</tr>